---
- hosts: 172.28.66.190
  remote_user: root
  become: true
  become_method: sudo
  gather_facts: yes
  tasks:
    - parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present
    - filesystem:
        fstype: ext4
        dev: /dev/sdb1
    - mount:
        fstype: ext4
        src: /dev/sdb1
        path: /app
        state: mounted
    - name: Copy Kafka RPM
      copy:
        src: kafka-2.11-2.0.0.x86_64.rpm
        dest: /tmp/kafka-2.11-2.0.0.x86_64.rpm
    - name: Install Kafka
      yum:
        name: /tmp/kafka-2.11-2.0.0.x86_64.rpm
        state: present
    - name: Enable Systemd Kafka Service
      systemd:
        name: kafka
        enabled: yes
        masked: no
    - name: Enable Systemd Zookeeper Service
      systemd:
        name: zookeeper
        enabled: yes
        masked: no
